ALTER TABLE `jpetstore`.`item` 
CHANGE COLUMN `attr1` `attr1` VARCHAR(255) NULL DEFAULT NULL  ,
CHANGE COLUMN `attr2` `attr2` VARCHAR(255) NULL DEFAULT NULL  , 
CHANGE COLUMN `attr3` `attr3` VARCHAR(255) NULL DEFAULT NULL  ,
CHANGE COLUMN `attr4` `attr4` VARCHAR(255) NULL DEFAULT NULL  , 
CHANGE COLUMN `attr5` `attr5` VARCHAR(255) NULL DEFAULT NULL  ;